site_name: 'PSLauncher'
site_description: 'Documentation for PowerShell Module: PSLauncher'
site_author: 'Pierre Smit'
site_url: 'https://smitpi.github.io/PSLauncher'
 
repo_url: 'https://github.com/smitpi/PSLauncher'
repo_name:  'smitpi/PSLauncher'
 
copyright: '(c) 2021 Pierre. All rights reserved.'
 
extra:
  manifest: manifest.webmanifest
  social:
    - icon: fontawesome/brands/github-square
      link: 'https://smitpi.github.io/PSLauncher'
 
markdown_extensions:
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
 
theme: windmill
