site_name: "PSLauncher"
site_description: "Documentation for PowerShell Module: PSLauncher"
site_author: "Pierre Smit"
site_url: "https://smitpi.github.io/PSLauncher"

repo_url: "https://github.com/smitpi/PSLauncher"
repo_name: "smitpi/PSLauncher"

copyright: "(c) 2021 Pierre. All rights reserved."

theme:
  name: null
  custom_dir: "cinder"
